### ISSUE TITLE
The VxRail PowerShell module cannot be found in the PowerShell Gallery

### ISSUE THREAD

**Issue by g-ali** [AsBuiltReport/AsBuiltReport.DellEMC.VxRail#3]
The notes refers to downloading the VxRail PowerShell module with a link to the PowerShell gallery. However the VxRail PowerShell module is not available in the PowerShell gallery as of the 5th of March 2021.

Is there any other location the VxRail PowerShell module can be downloaded from?

Thanks

**Comment by tpcarman** [comment]
Code within the `dev` branch of an AsBuiltReport repository, is considered in development.  When code is committed to the `master` branch it is considered ready for use, and will be published to the PowerShell Gallery. 

At this time, the VxRail module has not been widely tested and is here for others to test and provide feedback. 

Instructions to download and install the module from GitHub can be found [here](https://github.com/AsBuiltReport/AsBuiltReport.DellEMC.VxRail#github).
